#ifndef __AboutDialog__
#define __AboutDialog__

// $Id: AboutDialog.h,v 1.1.1.1 2012/03/25 23:06:55 camac Exp $

/**
@file
Subclass of AboutDialog_fb, which is generated by wxFormBuilder.
*/

/** Implementing ConfigDialog_fb */
class AboutDialog : public AboutDialog_fb
{
public:
   /** Constructor */
   AboutDialog( wxWindow* parent );
};

#endif // __AboutDialog__
