#ifndef __InfoDialog__
#define __InfoDialog__

// $Id: InfoDialog.h,v 1.1.1.1 2012/03/25 23:06:55 camac Exp $

/**
@file
Subclass of InfoDialog_fb, which is generated by wxFormBuilder.
*/

/** Implementing ConfigDialog_fb */
class InfoDialog : public InfoDialog_fb
{
public:
   /** Constructor */
   InfoDialog( wxWindow* parent );
};

#endif // __InfoDialog__
